In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df = pd.read_csv("tmdb_5000_credits.csv")
df.reset_index(inplace = True)
df.head()

,index,movie_id,title,cast,crew
0,0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
df.shape

(4803, 5)

In [4]:
features = ['movie_id' , 'title' , 'cast' , 'crew']
df[features].head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
df[features].isnull().values.any()

np.False_

In [6]:
def combine_features(row):
    return row['movie_id']+' '+row['title']+' '+row['cast']+' '+row['crew']

In [7]:
count_matrix = CountVectorizer().fit_transform(df['crew'])
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)

[[1.         0.95317455 0.98678375 ... 0.90460132 0.72243161 0.83699884]
 [0.95317455 1.         0.95960533 ... 0.94511902 0.74185023 0.87578137]
 [0.98678375 0.95960533 1.         ... 0.92009212 0.7326647  0.84834869]
 ...
 [0.90460132 0.94511902 0.92009212 ... 1.         0.72228544 0.87785039]
 [0.72243161 0.74185023 0.7326647  ... 0.72228544 1.         0.72011904]
 [0.83699884 0.87578137 0.84834869 ... 0.87785039 0.72011904 1.        ]]

In [8]:
cosine_sim.shape

(4803, 4803)

In [9]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
def get_index_from_title(title):
    return df[df.title == title]["index"].values[0]

In [10]:
movie_user_likes = "Avatar" 
movie_index = get_index_from_title(movie_user_likes)

similar_movies = list(enumerate(cosine_sim[movie_index]))

In [11]:
print(similar_movies)

[(0, np.float64(1.0000000000000087)), (1, np.float64(0.9531745494286907)), (2, np.float64(0.9867837456397707)), (3, np.float64(0.9758809552499962)), (4, np.float64(0.9647425605454233)), (5, np.float64(0.9382994584365597)), (6, np.float64(0.9648312448487268)), (7, np.float64(0.961318643472782)), (8, np.float64(0.9411368226608977)), (9, np.float64(0.9752230196966266)), (10, np.float64(0.9068749466819628)), (11, np.float64(0.9197994525897203)), (12, np.float64(0.9421646707804949)), (13, np.float64(0.9385618401934619)), (14, np.float64(0.9659973199479047)), (15, np.float64(0.9626429326788651)), (16, np.float64(0.9886807501314491)), (17, np.float64(0.9361002021849458)), (18, np.float64(0.9456131957073582)), (19, np.float64(0.9874612079187196)), (20, np.float64(0.9868461423111169)), (21, np.float64(0.9397330402801644)), (22, np.float64(0.9828797832546472)), (23, np.float64(0.9451264485944235)), (24, np.float64(0.964072539227126)), (25, np.float64(0.9525346247267591)), (26, np.float64(0.981735541410834)), (27, np.float64(0.9843376205500963)), (28, np.float64(0.9775782004218976)), (29, np.float64(0.9529743178898066)), (30, np.float64(0.9751980027838033)), (31, np.float64(0.936817332752612)), (32, np.float64(0.9309038123332124)), (33, np.float64(0.9560849314282038)), (34, np.float64(0.8893405344672143)), (35, np.float64(0.9572388290156764)), (36, np.float64(0.9806622814684812)), (37, np.float64(0.9605025500076189)), (38, np.float64(0.9805385616952382)), (39, np.float64(0.9330075363705272)), (40, np.float64(0.9602630239128537)), (41, np.float64(0.962067979724713)), (42, np.float64(0.9672443774955936)), (43, np.float64(0.9452048679474562)), (44, np.float64(0.9577882853072928)), (45, np.float64(0.9434616645338463)), (46, np.float64(0.9839260523453099)), (47, np.float64(0.9875911824834814)), (48, np.float64(0.9453974196236729)), (49, np.float64(0.9174816080586988)), (50, np.float64(0.9305272109956289)), (51, np.float64(0.9584444345982777)), (52, np.float64(0.9468506575250524)), (53, np.float64(0.914669907934019)), (54, np.float64(0.8751317464422387)), (55, np.float64(0.9533154386978016)), (56, np.float64(0.9822496244737003)), (57, np.float64(0.9677998498418531)), (58, np.float64(0.9366114623978273)), (59, np.float64(0.9887036894996746)), (60, np.float64(0.9248889507328948)), (61, np.float64(0.9884431778081103)), (62, np.float64(0.9267511635689685)), (63, np.float64(0.9511695079342481)), (64, np.float64(0.9743136096732955)), (65, np.float64(0.962102051110223)), (66, np.float64(0.967449364559134)), (67, np.float64(0.9114701812010011)), (68, np.float64(0.9340234890449236)), (69, np.float64(0.9721923584767387)), (70, np.float64(0.903697174042528)), (71, np.float64(0.950093285785841)), (72, np.float64(0.9702841442391129)), (73, np.float64(0.9310330983798383)), (74, np.float64(0.9856378277958052)), (75, np.float64(0.9712855931473097)), (76, np.float64(0.9472878834209272)), (77, np.float64(0.9620094950196515)), (78, np.float64(0.951080450908926)), (79, np.float64(0.938591880215484)), (80, np.float64(0.9650746226372595)), (81, np.float64(0.9410015844048815)), (82, np.float64(0.9860607962334424)), (83, np.float64(0.9766399098776607)), (84, np.float64(0.9854144267653364)), (85, np.float64(0.9541723953881107)), (86, np.float64(0.8711213083937508)), (87, np.float64(0.9642989945981018)), (88, np.float64(0.9533158290182047)), (89, np.float64(0.961518026764171)), (90, np.float64(0.9784627767495462)), (91, np.float64(0.9803396301446003)), (92, np.float64(0.9508257025423307)), (93, np.float64(0.9769657846104535)), (94, np.float64(0.9840920073159599)), (95, np.float64(0.9822552765509733)), (96, np.float64(0.9306645797810179)), (97, np.float64(0.9619874499737726)), (98, np.float64(0.950997010324264)), (99, np.float64(0.9775222834591671)), (100, np.float64(0.9880676080986792)), (101, np.float64(0.9516515924813861)), (102, np.float64(0.9749956801424057)), (103, np.float64(0.8843423991600864)), (104, np.float64(0.9252531076366213)), (105, np.float64(0.987613777120458)), (106, np.float64(0.9288187139144402)), (107, np.float64(0.9806250589317673)), (108, np.float64(0.9842140937497992)), (109, np.float64(0.951226184832813)), (110, np.float64(0.9820245322466288)), (111, np.float64(0.9498551990333771)), (112, np.float64(0.9789049710525519)), (113, np.float64(0.961521399161049)), (114, np.float64(0.9555613767936689)), (115, np.float64(0.9359801857682513)), (116, np.float64(0.9197099792043685)), (117, np.float64(0.9785177427684539)), (118, np.float64(0.9669859053195553)), (119, np.float64(0.9764713476151297)), (120, np.float64(0.8963861151783435)), (121, np.float64(0.9577724079739184)), (122, np.float64(0.9059156607600104)), (123, np.float64(0.9606779852273223)), (124, np.float64(0.9421228581568826)), (125, np.float64(0.9574341854098684)), (126, np.float64(0.9493727527877515)), (127, np.float64(0.9683521174992642)), (128, np.float64(0.9826117560082498)), (129, np.float64(0.9514639052540296)), (130, np.float64(0.9569378072526578)), (131, np.float64(0.9210747055229741)), (132, np.float64(0.95949033343455)), (133, np.float64(0.9057615777227667)), (134, np.float64(0.985846871406978)), (135, np.float64(0.9433257125763875)), (136, np.float64(0.9509087920616884)), (137, np.float64(0.9388916584971017)), (138, np.float64(0.7871712361540139)), (139, np.float64(0.9597588421014716)), (140, np.float64(0.9208998119597984)), (141, np.float64(0.8869378677420777)), (142, np.float64(0.9255427903618008)), (143, np.float64(0.9412153778482061)), (144, np.float64(0.9251734665438945)), (145, np.float64(0.9782483048873883)), (146, np.float64(0.9418254829377263)), (147, np.float64(0.8737884544135847)), (148, np.float64(0.9793121019509594)), (149, np.float64(0.985070111922186)), (150, np.float64(0.9775555347962571)), (151, np.float64(0.9759475208514343)), (152, np.float64(0.9510179994614757)), (153, np.float64(0.9057191674489141)), (154, np.float64(0.9318746251351955)), (155, np.float64(0.9459449516079974)), (156, np.float64(0.9041378709886355)), (157, np.float64(0.9889266246103936)), (158, np.float64(0.9414220318747248)), (159, np.float64(0.9792632577622411)), (160, np.float64(0.9390293393385795)), (161, np.float64(0.9718873534272483)), (162, np.float64(0.9310557726736529)), (163, np.float64(0.9470215318899843)), (164, np.float64(0.9691004879729036)), (165, np.float64(0.9776423094582583)), (166, np.float64(0.932939071759833)), (167, np.float64(0.9691380650205047)), (168, np.float64(0.9500279284845804)), (169, np.float64(0.9882584497275076)), (170, np.float64(0.933198409201564)), (171, np.float64(0.9809059040796168)), (172, np.float64(0.9845722220160809)), (173, np.float64(0.9382323619537813)), (174, np.float64(0.9593023585740155)), (175, np.float64(0.9184868166180181)), (176, np.float64(0.9844395958598595)), (177, np.float64(0.905654819843683)), (178, np.float64(0.9224747089451497)), (179, np.float64(0.8300980469731903)), (180, np.float64(0.9714153174920834)), (181, np.float64(0.9352044696942531)), (182, np.float64(0.9755671689089198)), (183, np.float64(0.9630461579802245)), (184, np.float64(0.952784650043964)), (185, np.float64(0.9769347739366536)), (186, np.float64(0.9760700190229192)), (187, np.float64(0.9234488412497968)), (188, np.float64(0.9336441181006715)), (189, np.float64(0.9684657422071704)), (190, np.float64(0.969404024375223)), (191, np.float64(0.9785897543135615)), (192, np.float64(0.9828690234498868)), (193, np.float64(0.9840666615529595)), (194, np.float64(0.9476013185758511)), (195, np.float64(0.984002579268665)), (196, np.float64(0.9198561330636249)), (197, np.float64(0.976245789130868)), (198, np.float64(0.9541999640602248)), (199, np.float64(0.9779418629773684)), (200, np.float64(0.9900858728637177)), (201, np.float64(0.9795248142624301)), (202, np.float64(0.9227885886236236)), (203, np.float64(0.9553380774105324)), (204, np.float64(0.9880148998656041)), (205, np.float64(0.9646144101365274)), (206, np.float64(0.9851671720349745)), (207, np.float64(0.9394390512489429)), (208, np.float64(0.9089905858654819)), (209, np.float64(0.9825780740002793)), (210, np.float64(0.9766471037929465)), (211, np.float64(0.9394779232698249)), (212, np.float64(0.9883792327776586)), (213, np.float64(0.9779195457684462)), (214, np.float64(0.9333195378251317)), (215, np.float64(0.9246945308539715)), (216, np.float64(0.9703467648634326)), (217, np.float64(0.963085656186409)), (218, np.float64(0.9813426773143938)), (219, np.float64(0.9183057980161311)), (220, np.float64(0.9783981427102577)), (221, np.float64(0.9272398807497807)), (222, np.float64(0.9864167121248737)), (223, np.float64(0.9750214380735194)), (224, np.float64(0.9508774556527219)), (225, np.float64(0.9120168584055075)), (226, np.float64(0.9338398415648491)), (227, np.float64(0.9725183910630758)), (228, np.float64(0.9323923670742031)), (229, np.float64(0.933723476410899)), (230, np.float64(0.9474131414154321)), (231, np.float64(0.9761723253430984)), (232, np.float64(0.964361015762251)), (233, np.float64(0.9380999433694543)), (234, np.float64(0.9379517080133644)), (235, np.float64(0.9260706170590535)), (236, np.float64(0.949049607734172)), (237, np.float64(0.8788464498587257)), (238, np.float64(0.9399869022857882)), (239, np.float64(0.9797889246811962)), (240, np.float64(0.9730191860781252)), (241, np.float64(0.8985929531785187)), (242, np.float64(0.9844897799099204)), (243, np.float64(0.9393968511873276)), (244, np.float64(0.9690059994601636)), (245, np.float64(0.9359129393538997)), (246, np.float64(0.9764560685797613)), (247, np.float64(0.9679393654854833)), (248, np.float64(0.9250521846635648)), (249, np.float64(0.9620755231201981)), (250, np.float64(0.9803645627737303)), (251, np.float64(0.9585888517764977)), (252, np.float64(0.9433061097072474)), (253, np.float64(0.9854518324799812)), (254, np.float64(0.9423463038919644)), (255, np.float64(0.9510164088151488)), (256, np.float64(0.9833041313151456)), (257, np.float64(0.9410177925548282)), (258, np.float64(0.9276855562489819)), (259, np.float64(0.9728816394384062)), (260, np.float64(0.9892608158166831)), (261, np.float64(0.9833595665608788)), (262, np.float64(0.937773539690612)), (263, np.float64(0.9737734984687828)), (264, np.float64(0.9395820700548676)), (265, np.float64(0.916937276066377)), (266, np.float64(0.9779064150513666)), (267, np.float64(0.9724158276706729)), (268, np.float64(0.8973780915633012)), (269, np.float64(0.9653393899722819)), (270, np.float64(0.9886163512025368)), (271, np.float64(0.9642715725782244)), (272, np.float64(0.8333095748466346)), (273, np.float64(0.938195588033739)), (274, np.float64(0.9748811451676712)), (275, np.float64(0.9768871803918153)), (276, np.float64(0.9811860512813156)), (277, np.float64(0.9755478796246513)), (278, np.float64(0.9478122795966303)), (279, np.float64(0.9698245692607534)), (280, np.float64(0.9761153994188113)), (281, np.float64(0.95531720238742)), (282, np.float64(0.9506979844685203)), (283, np.float64(0.9376794745225188)), (284, np.float64(0.8906435424787909)), (285, np.float64(0.8924956187443397)), (286, np.float64(0.975286593674523)), (287, np.float64(0.9669215832285022)), (288, np.float64(0.9568417497382017)), (289, np.float64(0.9443362193243208)), (290, np.float64(0.9815597888345222)), (291, np.float64(0.9735886296940324)), (292, np.float64(0.9578254998890906)), (293, np.float64(0.8668530022197094)), (294, np.float64(0.9517505394380249)), (295, np.float64(0.9219828462952467)), (296, np.float64(0.9801482273986563)), (297, np.float64(0.9795443548865689)), (298, np.float64(0.9745598549298095)), (299, np.float64(0.917946498225308)), (300, np.float64(0.945012870187066)), (301, np.float64(0.9891811359432942)), (302, np.float64(0.9381087398484028)), (303, np.float64(0.9771099035584678)), (304, np.float64(0.9809515982758674)), (305, np.float64(0.9473356285606396)), (306, np.float64(0.9182138168429087)), (307, np.float64(0.9856828860967201)), (308, np.float64(0.9776014031301723)), (309, np.float64(0.9430612373837319)), (310, np.float64(0.9880076433741577)), (311, np.float64(0.9003474352839076)), (312, np.float64(0.9760934810435077)), (313, np.float64(0.910537099438383)), (314, np.float64(0.9321031945460678)), (315, np.float64(0.911774109166951)), (316, np.float64(0.9209122283382943)), (317, np.float64(0.9607190802709091)), (318, np.float64(0.9213775455744347)), (319, np.float64(0.9210665249095477)), (320, np.float64(0.9738541137868729)), (321, np.float64(0.9120442004910172)), (322, np.float64(0.9759523579081405)), (323, np.float64(0.903650031641645)), (324, np.float64(0.9506920723817308)), (325, np.float64(0.9298417694023969)), (326, np.float64(0.9828556252477758)), (327, np.float64(0.9097665804798469)), (328, np.float64(0.9793390223451564)), (329, np.float64(0.9406018909604811)), (330, np.float64(0.9498644529005835)), (331, np.float64(0.9549365310351543)), (332, np.float64(0.955293078475599)), (333, np.float64(0.9696309466226475)), (334, np.float64(0.9765664575313538)), (335, np.float64(0.980069556440753)), (336, np.float64(0.9774416309700062)), (337, np.float64(0.9878412234531246)), (338, np.float64(0.9743521700374663)), (339, np.float64(0.9785484183540728)), (340, np.float64(0.9262089325819095)), (341, np.float64(0.9538391044755848)), (342, np.float64(0.9775473487622456)), (343, np.float64(0.9666941524836292)), (344, np.float64(0.9385286054219775)), (345, np.float64(0.9089498635011023)), (346, np.float64(0.9720986606840512)), (347, np.float64(0.9328028041434181)), (348, np.float64(0.9131312613894038)), (349, np.float64(0.9460370772498422)), (350, np.float64(0.9491313429108408)), (351, np.float64(0.9727519217080794)), (352, np.float64(0.956529536104282)), (353, np.float64(0.9391275636298688)), (354, np.float64(0.9867430049619701)), (355, np.float64(0.9740320476207934)), (356, np.float64(0.9214859091640969)), (357, np.float64(0.8756021793412171)), (358, np.float64(0.971628275882618)), (359, np.float64(0.9053199833004051)), (360, np.float64(0.949088328103904)), (361, np.float64(0.9176654361305134)), (362, np.float64(0.9325770850170669)), (363, np.float64(0.9812402385400407)), (364, np.float64(0.9309892934337705)), (365, np.float64(0.9848674849387031)), (366, np.float64(0.9105675058175012)), (367, np.float64(0.9703544189012359)), (368, np.float64(0.9638232190248357)), (369, np.float64(0.9211586663902744)), (370, np.float64(0.981728602200793)), (371, np.float64(0.9068698614562087)), (372, np.float64(0.956110550391083)), (373, np.float64(0.9550693117213265)), (374, np.float64(0.9118459072138918)), (375, np.float64(0.9298522538636145)), (376, np.float64(0.9102896041036065)), (377, np.float64(0.9278277379279125)), (378, np.float64(0.9022100828082903)), (379, np.float64(0.9637551020703228)), (380, np.float64(0.9637150805275247)), (381, np.float64(0.774291155150252)), (382, np.float64(0.9713214412422336)), (383, np.float64(0.9747812742802014)), (384, np.float64(0.8882355344118169)), (385, np.float64(0.9405439043815119)), (386, np.float64(0.9711686740719196)), (387, np.float64(0.9736824339901764)), (388, np.float64(0.9707820217979107)), (389, np.float64(0.9405458990651493)), (390, np.float64(0.9219740854554083)), (391, np.float64(0.9560257539612028)), (392, np.float64(0.9279413581613691)), (393, np.float64(0.9085085668726312)), (394, np.float64(0.9317057817630341)), (395, np.float64(0.9095764668891706)), (396, np.float64(0.9317847246905531)), (397, np.float64(0.9028215381478221)), (398, np.float64(0.9468481863969227)), (399, np.float64(0.9350378177255246)), (400, np.float64(0.9716263230536912)), (401, np.float64(0.9810085127968089)), (402, np.float64(0.9296629170261018)), (403, np.float64(0.9754549625630615)), (404, np.float64(0.9287453896770788)), (405, np.float64(0.9591061707097278)), (406, np.float64(0.9520408782614751)), (407, np.float64(0.9527411890450984)), (408, np.float64(0.9730840381696462)), (409, np.float64(0.918695240507412)), (410, np.float64(0.9171892008007554)), (411, np.float64(0.8745904630913395)), (412, np.float64(0.9856728837130653)), (413, np.float64(0.8926357153027061)), (414, np.float64(0.9811603375571197)), (415, np.float64(0.987884379255477)), (416, np.float64(0.9007277739136745)), (417, np.float64(0.9335098677985465)), (418, np.float64(0.928643585083681)), (419, np.float64(0.9664257816282252)), (420, np.float64(0.9023774871947507)), (421, np.float64(0.9440269133114664)), (422, np.float64(0.9820807269157948)), (423, np.float64(0.968908143874811)), (424, np.float64(0.9752718666014314)), (425, np.float64(0.9785312452913661)), (426, np.float64(0.9769184346433777)), (427, np.float64(0.8436066271021841)), (428, np.float64(0.935876889466438)), (429, np.float64(0.9146997098594375)), (430, np.float64(0.947325416236197)), (431, np.float64(0.947358080758631)), (432, np.float64(0.9779487497239969)), (433, np.float64(0.9153631023555584)), (434, np.float64(0.8760087943519489)), (435, np.float64(0.9162306924041754)), (436, np.float64(0.9213250979568146)), (437, np.float64(0.9017818770406725)), (438, np.float64(0.8733735183042832)), (439, np.float64(0.9458175305126851)), (440, np.float64(0.921486325417386)), (441, np.float64(0.9602644187252424)), (442, np.float64(0.9261237531613633)), (443, np.float64(0.846772979053774)), (444, np.float64(0.9690318015598255)), (445, np.float64(0.9458334719857939)), (446, np.float64(0.9527818257253091)), (447, np.float64(0.9815199220190641)), (448, np.float64(0.9709174856061704)), (449, np.float64(0.9825233694565904)), (450, np.float64(0.9195531672959831)), (451, np.float64(0.9792898276847074)), (452, np.float64(0.976621787927257)), (453, np.float64(0.9476554005327688)), (454, np.float64(0.9826451026605939)), (455, np.float64(0.9059354398586248)), (456, np.float64(0.9811789027731342)), (457, np.float64(0.9592374866508356)), (458, np.float64(0.9315486734106311)), (459, np.float64(0.946925498396776)), (460, np.float64(0.9046516784570604)), (461, np.float64(0.9756487799698534)), (462, np.float64(0.9708497827251902)), (463, np.float64(0.7740130333272814)), (464, np.float64(0.9203655893302567)), (465, np.float64(0.948875755194919)), (466, np.float64(0.9392631190874903)), (467, np.float64(0.94282667981312)), (468, np.float64(0.8903673437981979)), (469, np.float64(0.9287092304364445)), (470, np.float64(0.9047467962815608)), (471, np.float64(0.9017835313914971)), (472, np.float64(0.9736310734195918)), (473, np.float64(0.9546460976763089)), (474, np.float64(0.9392608917163331)), (475, np.float64(0.899160922831722)), (476, np.float64(0.959763782909609)), (477, np.float64(0.9318047547013183)), (478, np.float64(0.9691294074820967)), (479, np.float64(0.9304610568238593)), (480, np.float64(0.919889242136896)), (481, np.float64(0.9712422380654533)), (482, np.float64(0.857570560720853)), (483, np.float64(0.9755952845612802)), (484, np.float64(0.9084153842851159)), (485, np.float64(0.917416924977448)), (486, np.float64(0.9832941854835657)), (487, np.float64(0.9760674106887508)), (488, np.float64(0.9309127425149968)), (489, np.float64(0.9261372726456045)), (490, np.float64(0.9088670042609084)), (491, np.float64(0.9723171842585245)), (492, np.float64(0.8022899600826651)), (493, np.float64(0.9699925900585245)), (494, np.float64(0.9538372442479939)), (495, np.float64(0.9854263476775607)), (496, np.float64(0.9501526400732506)), (497, np.float64(0.8950009268800285)), (498, np.float64(0.9790142307193287)), (499, np.float64(0.9444888345793931)), (500, np.float64(0.9765354047807697)), (501, np.float64(0.8680698248834794)), (502, np.float64(0.9116634266955201)), (503, np.float64(0.9167272622171962)), (504, np.float64(0.9630598267157218)), (505, np.float64(0.9808976350240989)), (506, np.float64(0.9673045659275887)), (507, np.float64(0.9754209467133161)), (508, np.float64(0.971924166651273)), (509, np.float64(0.9640879794438123)), (510, np.float64(0.9808830768331912)), (511, np.float64(0.9509457419321232)), (512, np.float64(0.9319182188778843)), (513, np.float64(0.9432327052765708)), (514, np.float64(0.9406711467130228)), (515, np.float64(0.9712940924970552)), (516, np.float64(0.9282006180663968)), (517, np.float64(

In [12]:
sorted_similar_movies = sorted(similar_movies , key = lambda x:x[1] , reverse=(True))

In [13]:
i = 0
print("Top 7 similar movies to "+movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>=7:
        break

Top 7 similar movies to Avatar are:

Avatar
The Hunger Games: Mockingjay - Part 1
Ender's Game
Cloud Atlas
Exodus: Gods and Kings
2012
The Avengers